package store

import (
	"fmt"
	"time"

	"gitlab2024.bds421-cloud.com/bds421/rho/tkg/v4/pkg/types"
)

// ValidateNodeSnapshotKey verifies that a node snapshot is stored under its
// own ID.
func ValidateNodeSnapshotKey(id types.NodeID, n *types.Node) error {
	if n == nil {
		return fmt.Errorf("%w: nil node snapshot", ErrInvalidStoreMutation)
	}
	if err := ValidateNodeID(id); err != nil {
		return err
	}
	if n.ID() != id {
		return fmt.Errorf("%w: node snapshot ID %d does not match key %d", ErrInvalidStoreMutation, n.ID(), id)
	}
	return nil
}

// ValidateRelSnapshotKey verifies that a relationship snapshot is stored under
// its own ID.
func ValidateRelSnapshotKey(id types.RelID, r *types.Relationship) error {
	if r == nil {
		return fmt.Errorf("%w: nil relationship snapshot", ErrInvalidStoreMutation)
	}
	if err := ValidateRelID(id); err != nil {
		return err
	}
	if r.ID() != id {
		return fmt.Errorf("%w: relationship snapshot ID %d does not match key %d", ErrInvalidStoreMutation, r.ID(), id)
	}
	return nil
}

// ValidateNodeHistorySnapshot verifies that a node payload can be stored as a
// version-history or tombstone snapshot under id.
func ValidateNodeHistorySnapshot(id types.NodeID, n *types.Node) error {
	if err := ValidateNodeSnapshotKey(id, n); err != nil {
		return err
	}
	if err := validateNodeLabels(n); err != nil {
		return err
	}
	return validateNodeExplicitTemporalRange(n.ID(), n.Temporal())
}

// ValidateNodeHistoryVersionSnapshot verifies that a node payload can be
// stored under the exact version-history key requested by the caller.
func ValidateNodeHistoryVersionSnapshot(id types.NodeID, version uint32, n *types.Node) error {
	return ValidateNodeHistoryKeySnapshot(id, uint64(version), n)
}

// ValidateNodeHistoryKeySnapshot verifies a decoded node history row against
// its full key. Badger history keys encode the version as uint64 even though
// public entity versions are uint32, so this helper rejects impossible key
// versions before callers can truncate them.
func ValidateNodeHistoryKeySnapshot(id types.NodeID, version uint64, n *types.Node) error {
	if err := ValidateNodeHistorySnapshot(id, n); err != nil {
		return err
	}
	if got := uint64(n.Version()); got != version {
		return fmt.Errorf("%w: node history payload version %d does not match key version %d", ErrInvalidStoreMutation, got, version)
	}
	return nil
}

// ValidateRelationshipHistorySnapshot verifies that a relationship payload can
// be stored as a version-history or tombstone snapshot under id.
func ValidateRelationshipHistorySnapshot(id types.RelID, r *types.Relationship) error {
	if err := ValidateRelSnapshotKey(id, r); err != nil {
		return err
	}
	if err := ValidateRelationshipIndexEntry(r.StartNodeID(), r.EndNodeID(), r.TypeToken().Value(), r.ID()); err != nil {
		return err
	}
	return validateRelExplicitTemporalRange(r.ID(), r.Temporal())
}

// ValidateRelationshipHistoryVersionSnapshot verifies that a relationship
// payload can be stored under the exact version-history key requested by the
// caller.
func ValidateRelationshipHistoryVersionSnapshot(id types.RelID, version uint32, r *types.Relationship) error {
	return ValidateRelationshipHistoryKeySnapshot(id, uint64(version), r)
}

// ValidateRelationshipHistoryKeySnapshot verifies a decoded relationship
// history row against its full key.
func ValidateRelationshipHistoryKeySnapshot(id types.RelID, version uint64, r *types.Relationship) error {
	if err := ValidateRelationshipHistorySnapshot(id, r); err != nil {
		return err
	}
	if got := uint64(r.Version()); got != version {
		return fmt.Errorf("%w: relationship history payload version %d does not match key version %d", ErrInvalidStoreMutation, got, version)
	}
	return nil
}

// ValidateNodeLiveVersion verifies that a history-writing mutation was derived
// from the currently stored node version.
func ValidateNodeLiveVersion(n *types.Node, version uint32) error {
	if n == nil {
		return fmt.Errorf("%w: nil existing node", ErrInvalidStoreMutation)
	}
	if n.Version() != version {
		return fmt.Errorf("%w: live node version %d does not match previous version %d", ErrInvalidStoreMutation, n.Version(), version)
	}
	return nil
}

// ValidateRelationshipLiveVersion verifies that a history-writing mutation was
// derived from the currently stored relationship version.
func ValidateRelationshipLiveVersion(r *types.Relationship, version uint32) error {
	if r == nil {
		return fmt.Errorf("%w: nil existing relationship", ErrInvalidStoreMutation)
	}
	if r.Version() != version {
		return fmt.Errorf("%w: live relationship version %d does not match previous version %d", ErrInvalidStoreMutation, r.Version(), version)
	}
	return nil
}

// ValidateNodeID verifies that a Store mutation targets a real node ID.
// Snowflake IDs generated by this library are strictly positive: 0 is an API
// sentinel, and negative values violate the snowflake sign-bit invariant.
func ValidateNodeID(id types.NodeID) error {
	if id == 0 {
		return fmt.Errorf("%w: zero node ID", ErrInvalidStoreMutation)
	}
	if id < 0 {
		return fmt.Errorf("%w: negative node ID %d", ErrInvalidStoreMutation, id)
	}
	return nil
}

// ValidateRelID verifies that a Store mutation targets a real relationship ID.
// Snowflake IDs generated by this library are strictly positive: 0 is an API
// sentinel, and negative values violate the snowflake sign-bit invariant.
func ValidateRelID(id types.RelID) error {
	if id == 0 {
		return fmt.Errorf("%w: zero relationship ID", ErrInvalidStoreMutation)
	}
	if id < 0 {
		return fmt.Errorf("%w: negative relationship ID %d", ErrInvalidStoreMutation, id)
	}
	return nil
}

// ValidateNodeWrite verifies that a current node payload can enter Store state.
func ValidateNodeWrite(n *types.Node) error {
	if n == nil {
		return fmt.Errorf("%w: nil node", ErrInvalidStoreMutation)
	}
	if err := ValidateNodeID(n.ID()); err != nil {
		return err
	}
	if err := validateNodeLabels(n); err != nil {
		return err
	}
	return validateNodeExplicitTemporalRange(n.ID(), n.Temporal())
}

func validateNodeLabels(n *types.Node) error {
	count := n.LabelTokenCount()
	if count == 0 {
		return fmt.Errorf("%w: node %d has no labels", ErrInvalidStoreMutation, n.ID())
	}
	for i := 0; i < count; i++ {
		tok := n.LabelTokenRawAt(i)
		if err := ValidateLabelToken(tok); err != nil {
			return fmt.Errorf("%w: invalid node label token %d for %d", err, tok, n.ID())
		}
	}
	return nil
}

// ValidateNodeReplacement verifies that replacement rows preserve the label
// tokens that back node secondary indexes and tiered-store routing.
func ValidateNodeReplacement(old, current *types.Node) error {
	if old == nil {
		return fmt.Errorf("%w: nil existing node", ErrInvalidStoreMutation)
	}
	if err := ValidateNodeHistorySnapshot(old.ID(), current); err != nil {
		return err
	}
	if old.LabelTokenCount() != current.LabelTokenCount() {
		return fmt.Errorf("%w: node labels changed for %d", ErrInvalidStoreMutation, old.ID())
	}
	if old.PrimaryLabelToken() != current.PrimaryLabelToken() {
		return fmt.Errorf("%w: node labels changed for %d", ErrInvalidStoreMutation, old.ID())
	}
	for i := 1; i < old.LabelTokenCount(); i++ {
		if old.LabelTokenRawAt(i) != current.LabelTokenRawAt(i) {
			return fmt.Errorf("%w: node labels changed for %d", ErrInvalidStoreMutation, old.ID())
		}
	}
	return nil
}

// ValidateNodeLabelRemoval verifies that a label-helper write removes exactly
// tok from the stored node's label set and does not smuggle any other label
// mutation through the current-row payload.
func ValidateNodeLabelRemoval(old, current *types.Node, tok uint16) error {
	if err := validateNodeLabelMutation(old, current, tok); err != nil {
		return err
	}
	if !old.HasLabelTokenRaw(tok) {
		return fmt.Errorf("%w: node %d does not have label token %d", ErrInvalidStoreMutation, old.ID(), tok)
	}
	if current.HasLabelTokenRaw(tok) {
		return fmt.Errorf("%w: node %d still has removed label token %d", ErrInvalidStoreMutation, old.ID(), tok)
	}
	if current.LabelTokenCount() != old.LabelTokenCount()-1 {
		return fmt.Errorf("%w: node labels changed beyond removal of token %d for %d", ErrInvalidStoreMutation, tok, old.ID())
	}
	for i := 0; i < old.LabelTokenCount(); i++ {
		label := old.LabelTokenRawAt(i)
		if label == tok {
			continue
		}
		if !current.HasLabelTokenRaw(label) {
			return fmt.Errorf("%w: node labels changed beyond removal of token %d for %d", ErrInvalidStoreMutation, tok, old.ID())
		}
	}
	return nil
}

// ValidateNodeLabelAddition verifies that a label-helper write adds exactly tok
// to the stored node's label set and preserves every existing label.
func ValidateNodeLabelAddition(old, current *types.Node, tok uint16) error {
	if err := validateNodeLabelMutation(old, current, tok); err != nil {
		return err
	}
	if old.HasLabelTokenRaw(tok) {
		return fmt.Errorf("%w: node %d already has label token %d", ErrInvalidStoreMutation, old.ID(), tok)
	}
	if !current.HasLabelTokenRaw(tok) {
		return fmt.Errorf("%w: node %d is missing added label token %d", ErrInvalidStoreMutation, old.ID(), tok)
	}
	if current.LabelTokenCount() != old.LabelTokenCount()+1 {
		return fmt.Errorf("%w: node labels changed beyond addition of token %d for %d", ErrInvalidStoreMutation, tok, old.ID())
	}
	for i := 0; i < old.LabelTokenCount(); i++ {
		if !current.HasLabelTokenRaw(old.LabelTokenRawAt(i)) {
			return fmt.Errorf("%w: node labels changed beyond addition of token %d for %d", ErrInvalidStoreMutation, tok, old.ID())
		}
	}
	return nil
}

func validateNodeLabelMutation(old, current *types.Node, tok uint16) error {
	if old == nil {
		return fmt.Errorf("%w: nil existing node", ErrInvalidStoreMutation)
	}
	if err := ValidateNodeHistorySnapshot(old.ID(), current); err != nil {
		return err
	}
	return ValidateLabelToken(tok)
}

// ValidateRelationshipWrite verifies that a current relationship payload can
// enter Store state.
func ValidateRelationshipWrite(r *types.Relationship) error {
	if r == nil {
		return fmt.Errorf("%w: nil relationship", ErrInvalidStoreMutation)
	}
	id := r.ID()
	if err := ValidateRelID(id); err != nil {
		return err
	}
	if err := ValidateRelTypeToken(r.TypeToken().Value()); err != nil {
		return err
	}
	if err := ValidateNodeID(r.StartNodeID()); err != nil {
		return fmt.Errorf("%w: invalid relationship start node ID %d", err, r.StartNodeID())
	}
	if err := ValidateNodeID(r.EndNodeID()); err != nil {
		return fmt.Errorf("%w: invalid relationship end node ID %d", err, r.EndNodeID())
	}
	return validateRelExplicitTemporalRange(id, r.Temporal())
}

func validateNodeExplicitTemporalRange(id types.NodeID, tm *types.TemporalMetadata) error {
	if tm == nil {
		return nil
	}
	if tm.ValidFrom != 0 && tm.ValidTo != 0 && tm.ValidFrom >= tm.ValidTo {
		return fmt.Errorf("%w: node %d valid_from %d must be before valid_to %d", ErrInvalidStoreMutation, id, tm.ValidFrom, tm.ValidTo)
	}
	return nil
}

func validateRelExplicitTemporalRange(id types.RelID, tm *types.TemporalMetadata) error {
	if tm == nil {
		return nil
	}
	if tm.ValidFrom != 0 && tm.ValidTo != 0 && tm.ValidFrom >= tm.ValidTo {
		return fmt.Errorf("%w: relationship %d valid_from %d must be before valid_to %d", ErrInvalidStoreMutation, id, tm.ValidFrom, tm.ValidTo)
	}
	return nil
}

// ValidateRelationshipIndexEntry verifies the fields that identify a
// relationship's type and adjacency index rows.
func ValidateRelationshipIndexEntry(startID, endID types.NodeID, relType uint16, relID types.RelID) error {
	if err := ValidateRelID(relID); err != nil {
		return err
	}
	if err := ValidateRelTypeToken(relType); err != nil {
		return err
	}
	if err := ValidateNodeID(startID); err != nil {
		return fmt.Errorf("%w: invalid relationship start node ID %d", err, startID)
	}
	if err := ValidateNodeID(endID); err != nil {
		return fmt.Errorf("%w: invalid relationship end node ID %d", err, endID)
	}
	return nil
}

// ValidateRelTypeToken verifies that a Store-level relationship query or index
// operation targets a real relationship type token.
func ValidateRelTypeToken(relType uint16) error {
	if relType == 0 {
		return fmt.Errorf("%w: zero relationship type token", ErrInvalidStoreMutation)
	}
	return nil
}

// ValidateLabelToken verifies that a Store-level index operation targets a
// real label token. Token 0 is reserved by the registry and must never identify
// a persisted index definition.
func ValidateLabelToken(labelToken uint16) error {
	if labelToken == 0 {
		return fmt.Errorf("%w: zero label token", ErrInvalidStoreMutation)
	}
	return nil
}

// ValidateShardDepth verifies that a QueryOpts.Depth value is one of the
// defined shard-depth selectors. Single-shard stores may treat valid depth
// selectors equivalently, but unknown enum values must fail closed.
func ValidateShardDepth(depth ShardDepth) error {
	switch depth {
	case DepthAll, DepthHot, DepthWarm:
		return nil
	default:
		return fmt.Errorf("%w: %d", ErrInvalidShardDepth, depth)
	}
}

// ValidateQueryOpts verifies the shared query-option invariants enforced by
// every Store query surface.
func ValidateQueryOpts(opts QueryOpts) error {
	if err := ValidateShardDepth(opts.Depth); err != nil {
		return err
	}
	if err := ValidatePagination(opts.After, opts.Limit); err != nil {
		return err
	}
	if opts.ValidAt == 0 && opts.ValidStart > 0 && opts.ValidEnd > 0 && opts.ValidStart >= opts.ValidEnd {
		return fmt.Errorf("%w: start %d >= end %d", ErrInvalidTimeRange, opts.ValidStart, opts.ValidEnd)
	}
	return nil
}

// ValidatePagination verifies the shared cursor/limit invariants used by
// QueryOpts-backed query methods and raw cursor-paginated history scans.
func ValidatePagination(after types.EntityID, limit int) error {
	if limit < 0 {
		return fmt.Errorf("%w: %d", ErrInvalidQueryLimit, limit)
	}
	if after < 0 {
		return fmt.Errorf("%w: %d", ErrInvalidQueryCursor, after)
	}
	return nil
}

// ValidateHistoryRetention verifies the retention count for history
// truncation. Zero is an explicit "clear all history" request; negative
// retention is invalid and must not be treated as a destructive clear-all.
func ValidateHistoryRetention(keepVersions int) error {
	if keepVersions < 0 {
		return fmt.Errorf("%w: negative history retention %d", ErrInvalidStoreMutation, keepVersions)
	}
	return nil
}

// ValidateHistoryPageLimit verifies the page size for per-entity history
// version scans. Zero means "all remaining" to match the other Store cursor
// APIs; negative limits are invalid.
func ValidateHistoryPageLimit(limit int) error {
	if limit < 0 {
		return fmt.Errorf("%w: %d", ErrInvalidQueryLimit, limit)
	}
	return nil
}

// ValidateIndexPropertyKey verifies that Store-level property/vector index
// operations target a real stored property key. Shadow keys are resolved by the
// Graph layer and are never stored in PropertySlice, so indexing them would
// create a durable no-op definition.
func ValidateIndexPropertyKey(propertyKey string) error {
	if types.IsShadowKey(propertyKey) {
		return fmt.Errorf("%w: %q", types.ErrReservedPrefix, propertyKey)
	}
	return nil
}

// ValidateHighFrequencyBucketSize verifies that an HFI bucket width can be
// represented exactly by the millisecond Instant precision used by temporal
// indexes.
func ValidateHighFrequencyBucketSize(bucketSize time.Duration) error {
	if bucketSize <= 0 {
		return fmt.Errorf("%w: high-frequency bucket size must be positive, got %v", ErrInvalidTemporalIndexConfig, bucketSize)
	}
	if bucketSize < time.Millisecond || bucketSize%time.Millisecond != 0 {
		return fmt.Errorf("%w: high-frequency bucket size must be a whole millisecond, got %v", ErrInvalidTemporalIndexConfig, bucketSize)
	}
	return nil
}

// ValidateRelationshipReplacement verifies that replacement rows preserve the
// fields that back relationship secondary indexes.
func ValidateRelationshipReplacement(old, current *types.Relationship) error {
	if old == nil {
		return fmt.Errorf("%w: nil existing relationship", ErrInvalidStoreMutation)
	}
	if err := ValidateRelSnapshotKey(old.ID(), current); err != nil {
		return err
	}
	if err := ValidateRelationshipWrite(current); err != nil {
		return err
	}
	if old.TypeToken().Value() != current.TypeToken().Value() {
		return fmt.Errorf("%w: relationship type token changed from %d to %d", ErrInvalidStoreMutation, old.TypeToken().Value(), current.TypeToken().Value())
	}
	if old.StartNodeID() != current.StartNodeID() {
		return fmt.Errorf("%w: relationship start node changed from %d to %d", ErrInvalidStoreMutation, old.StartNodeID(), current.StartNodeID())
	}
	if old.EndNodeID() != current.EndNodeID() {
		return fmt.Errorf("%w: relationship end node changed from %d to %d", ErrInvalidStoreMutation, old.EndNodeID(), current.EndNodeID())
	}
	return nil
}
