package core

import (
	"bytes"
	"compress/gzip"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/data-insights-ai/rho-tkg/v4/pkg/types"
)

// GUARD (backlog 43): chains written without any retraction — every delete
// shape the plain and caller-instant doors produce — answer EXACTLY as they
// did before the retraction existed. The golden file was generated by THIS
// test run against the code before the retraction (main at fc90801, the
// v4.49.0 resolver), in a scratch checkout, with OLDCHAIN_GOLDEN_WRITE=1; the
// rendering prints every observable stamp explicitly (no struct printing, so
// a new field cannot change it). Catches a retraction rule that leaks into
// chains without a marker (a changed life rule, a changed normalizer, a
// dropped row).
//
// The test clock is a fixed constant, every valid-from explicit and entities
// are rendered by creation ordinal, so the answers do not depend on the wall
// clock or the minted IDs.
func TestRetraction_OldChainsAnswerAsBefore(t *testing.T) {
	t.Parallel()
	got := map[string]string{}
	for _, be := range txbBackends() {
		got[be.name] = oldChainAnswers(t, be.open(t, true))
	}
	for name, s := range got {
		if s != got["memory"] {
			t.Fatalf("%s answers differ from memory:%s", name, oldChainDiff(got["memory"], s))
		}
	}
	path := filepath.Join("testdata", "retraction_oldchain_golden.txt.gz")
	if os.Getenv("OLDCHAIN_GOLDEN_WRITE") == "1" {
		if err := os.MkdirAll("testdata", 0o750); err != nil {
			t.Fatal(err)
		}
		var buf bytes.Buffer
		zw, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := zw.Write([]byte(got["memory"])); err != nil {
			t.Fatal(err)
		}
		if err := zw.Close(); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, buf.Bytes(), 0o600); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d lines)", path, strings.Count(got["memory"], "\n"))
		return
	}
	raw, err := os.ReadFile(path) // #nosec G304 -- fixed test path
	if err != nil {
		t.Fatalf("golden: %v", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		t.Fatalf("golden: %v", err)
	}
	want, err := io.ReadAll(zr)
	if err != nil {
		t.Fatalf("golden: %v", err)
	}
	if got["memory"] != string(want) {
		t.Fatalf("chains without a retraction answer differently than before:%s", oldChainDiff(string(want), got["memory"]))
	}
}

func oldChainDiff(a, b string) string {
	al, bl := strings.Split(a, "\n"), strings.Split(b, "\n")
	var out strings.Builder
	n := 0
	for i := 0; i < max(len(al), len(bl)) && n < 20; i++ {
		var x, y string
		if i < len(al) {
			x = al[i]
		}
		if i < len(bl) {
			y = bl[i]
		}
		if x != y {
			fmt.Fprintf(&out, "\n line %d\n  want %s\n  got  %s", i, x, y)
			n++
		}
	}
	return out.String()
}

func ocTemporal(tm *types.TemporalMetadata) string {
	if tm == nil {
		return "-"
	}
	return fmt.Sprintf("vf=%d vt=%d tf=%d tt=%d ca=%d ua=%d da=%d", tm.ValidFrom, tm.ValidTo, tm.TxFrom, tm.TxTo, tm.CreatedAt, tm.UpdatedAt, tm.DeletedAt)
}

func ocProps(ps types.PropertySlice) string {
	parts := make([]string, 0, len(ps))
	for _, p := range ps {
		parts = append(parts, fmt.Sprintf("%s=%v", p.Key, p.Value))
	}
	slices.Sort(parts)
	return strings.Join(parts, ",")
}

// oldChainAnswers builds the fixtures on g and renders what the state,
// record and timeline doors answer at every recorded instant (and ±1) and a
// grid of valid instants.
func oldChainAnswers(t *testing.T, g *Core) string {
	t.Helper()
	ctx := context.Background()
	clk := &switchableClock{}
	g.SetClockForTest(t, clk.Now)
	x := types.Instant(1_900_000_000_000) // 2030-03-17: above the wall clock
	tick := func() { x += 1000; clk.at.Store(int64(x)) }
	tick()

	var nodes []types.NodeID
	var rels []types.RelID
	must := func(what string, err error) {
		t.Helper()
		if err != nil {
			t.Fatalf("fixture %s: %v", what, err)
		}
	}
	add := func(label string, k int, vf types.Instant) types.NodeID {
		n, err := g.Nodes.Add(ctx, []string{label}, map[string]any{"k": k, "tkg_valid_from": vf})
		must("Add", err)
		nodes = append(nodes, n.ID())
		tick()
		return n.ID()
	}
	link := func(s, e types.NodeID, k int, vf types.Instant) types.RelID {
		r, err := g.Rels.AddByID(ctx, "LINK", s, e, map[string]any{"k": k, "tkg_valid_from": vf})
		must("AddByID", err)
		rels = append(rels, r.ID())
		tick()
		return r.ID()
	}
	ref := add("Ref", 0, 1000)
	ev := add("Ev", 0, 1000)

	// a. add, update, delete.
	a := add("A", 1, 1000)
	_, err := g.Nodes.Update(ctx, a, map[string]any{"k": 2, "tkg_valid_from": types.Instant(2000)})
	must("Update a", err)
	tick()
	must("Delete a", g.Nodes.Delete(ctx, a))
	tick()

	// b. a bounded cascade (the slot row below the appended rows), then delete.
	b := add("A", 3, 1000)
	_, err = g.Temporal.SetNodeVersionInterval(ctx, b, 1500, 1800, map[string]any{"k": 4})
	must("cascade b", err)
	tick()
	must("Delete b", g.Nodes.Delete(ctx, b))
	tick()

	// c. a recorded close, then delete.
	c := add("A", 5, 1000)
	must("Close c", g.Nodes.CloseVersion(ctx, c, 3000))
	tick()
	must("Delete c", g.Nodes.Delete(ctx, c))
	tick()

	// d. delete, re-import valid from below the first life, update inside it,
	// delete again.
	d := add("A", 6, 1000)
	must("Delete d", g.Nodes.Delete(ctx, d))
	tick()
	_, err = g.Nodes.Import(ctx, d, []string{"A"}, map[string]any{"k": 7, "tkg_valid_from": types.Instant(500)})
	must("Import d", err)
	tick()
	_, err = g.Nodes.Update(ctx, d, map[string]any{"k": 8, "tkg_valid_from": types.Instant(2500)})
	must("Update d", err)
	tick()
	must("Delete d again", g.Nodes.Delete(ctx, d))
	tick()

	// e. a node delete cascading to its relationships (one updated).
	e := add("A", 9, 1000)
	r1 := link(ref, e, 1, 1000)
	link(e, ev, 2, 1200)
	_, err = g.Rels.Update(ctx, r1, map[string]any{"k": 3, "tkg_valid_from": types.Instant(2200)})
	must("Rels.Update", err)
	tick()
	must("Delete e", g.Nodes.Delete(ctx, e))
	tick()

	// f. a relationship: cascade, delete, re-import, delete.
	r2 := link(ref, ev, 4, 1000)
	_, err = g.Temporal.SetRelVersionInterval(ctx, r2, 1100, 0, map[string]any{"k": 5})
	must("cascade r2", err)
	tick()
	must("Rels.Delete r2", g.Rels.Delete(ctx, r2))
	tick()
	sn, err := g.Nodes.Get(ctx, ref)
	must("Get ref", err)
	en, err := g.Nodes.Get(ctx, ev)
	must("Get ev", err)
	_, err = g.Rels.Import(ctx, r2, "LINK", sn, en, map[string]any{"k": 6, "tkg_valid_from": types.Instant(600)})
	must("Rels.Import r2", err)
	tick()
	must("Rels.Delete r2 again", g.Rels.Delete(ctx, r2))
	tick()

	// g. caller-instant ends: DeleteWithTx on a node and a relationship.
	h := add("A", 10, 1000)
	r3 := link(ref, ev, 7, 1000)
	tick()
	must("DeleteWithTx h", g.Nodes.DeleteWithTx(ctx, h, x-500))
	must("Rels.DeleteWithTx r3", g.Rels.DeleteWithTx(ctx, r3, x-400))
	tick()

	ord := map[string]string{}
	for i, id := range nodes {
		ord["n:"+fmt.Sprint(id)] = fmt.Sprintf("n%d", i)
	}
	for i, id := range rels {
		ord["r:"+fmt.Sprint(id)] = fmt.Sprintf("r%d", i)
	}
	nodeSet := func(ns []*types.Node, err error) string {
		if err != nil {
			return "err:" + err.Error()
		}
		out := make([]string, 0, len(ns))
		for _, n := range ns {
			out = append(out, fmt.Sprintf("%s v%d %s {%s}", ord["n:"+fmt.Sprint(n.ID())], n.Version(), ocTemporal(n.Temporal()), ocProps(n.Properties())))
		}
		slices.Sort(out)
		return strings.Join(out, "; ")
	}
	relSet := func(rs []*types.Relationship, err error) string {
		if err != nil {
			return "err:" + err.Error()
		}
		out := make([]string, 0, len(rs))
		for _, r := range rs {
			out = append(out, fmt.Sprintf("%s v%d %s {%s}", ord["r:"+fmt.Sprint(r.ID())], r.Version(), ocTemporal(r.Temporal()), ocProps(r.Properties())))
		}
		slices.Sort(out)
		return strings.Join(out, "; ")
	}

	pinSet := map[types.Instant]bool{0: true}
	validSet := map[types.Instant]bool{1: true}
	stamp := func(tm *types.TemporalMetadata) {
		if tm == nil {
			return
		}
		for _, v := range []types.Instant{tm.TxFrom, tm.TxTo, tm.DeletedAt, tm.UpdatedAt} {
			if v > 0 {
				pinSet[v-1], pinSet[v] = true, true
			}
		}
		for _, v := range []types.Instant{tm.ValidFrom, tm.ValidTo} {
			if v > 1 {
				validSet[v-1], validSet[v] = true, true
			}
		}
	}
	for _, id := range nodes {
		hist, err := g.Nodes.History(id)
		must("History", err)
		for _, r := range hist {
			stamp(r.Temporal())
		}
		if cur, err := g.Nodes.Get(ctx, id); err == nil {
			stamp(cur.Temporal())
		}
	}
	for _, id := range rels {
		hist, err := g.Rels.History(id)
		must("Rels.History", err)
		for _, r := range hist {
			stamp(r.Temporal())
		}
		if cur, err := g.Rels.Get(ctx, id); err == nil {
			stamp(cur.Temporal())
		}
	}
	peek, err := g.Temporal.PeekTx()
	must("PeekTx", err)
	var pins, valids []types.Instant
	for p := range pinSet {
		if p <= peek {
			pins = append(pins, p)
		}
	}
	for v := range validSet {
		valids = append(valids, v)
	}
	slices.Sort(pins)
	slices.Sort(valids)

	var out strings.Builder
	for _, pin := range pins {
		for _, v := range valids {
			fmt.Fprintf(&out, "pin=%d v=%d NodesAtTx: %s\n", pin, v, nodeSet(g.Temporal.NodesAtTx(v, pin)))
			fmt.Fprintf(&out, "pin=%d v=%d RelsAtTx: %s\n", pin, v, relSet(g.Temporal.RelsAtTx(v, pin)))
			fmt.Fprintf(&out, "pin=%d v=%d NodesDuringTx: %s\n", pin, v, nodeSet(g.Temporal.NodesDuringTx(v, v+250, pin)))
			fmt.Fprintf(&out, "pin=%d v=%d RelsDuringTx: %s\n", pin, v, relSet(g.Temporal.RelsDuringTx(v, v+250, pin)))
		}
		if pin == 0 {
			continue
		}
		fmt.Fprintf(&out, "pin=%d NodesAsOf: %s\n", pin, nodeSet(g.Temporal.NodesAsOf(pin)))
		fmt.Fprintf(&out, "pin=%d RelsAsOf: %s\n", pin, relSet(g.Temporal.RelsAsOf(pin)))
		for _, id := range nodes {
			segs, err := g.Temporal.NodeEffectiveTimeline(id, pin)
			var parts []string
			for _, s := range segs {
				parts = append(parts, fmt.Sprintf("[%d,%d) v%d %s", s.ValidFrom, s.ValidTo, s.Node.Version(), ocTemporal(s.Node.Temporal())))
			}
			fmt.Fprintf(&out, "pin=%d timeline %s: %s err=%v\n", pin, ord["n:"+fmt.Sprint(id)], strings.Join(parts, " | "), err)
		}
		for _, id := range rels {
			segs, err := g.Temporal.RelEffectiveTimeline(id, pin)
			var parts []string
			for _, s := range segs {
				parts = append(parts, fmt.Sprintf("[%d,%d) v%d %s", s.ValidFrom, s.ValidTo, s.Rel.Version(), ocTemporal(s.Rel.Temporal())))
			}
			fmt.Fprintf(&out, "pin=%d timeline %s: %s err=%v\n", pin, ord["r:"+fmt.Sprint(id)], strings.Join(parts, " | "), err)
		}
	}
	return out.String()
}
